theme: jekyll-theme-cayman
title: Welcome to my kbeznak parmatonic page!
description: This page is designed for promoting the search resuls on Google and Bing for query "kbeznak parmatonic" as a part of homework assignment for CSCE-670 Information retrieval course in Texas A&M University.
Feel free to bookmark this page to get more updates on kbeznak parmatonic !
url: http://aratna.github.io/
author: Abhinav Ratna
twitter:
  username: RatnaAbhi
facebook:
 publisher: https://www.facebook.com/abhinav.ratna.9
